ci:
  autofix_commit_msg: "chore(pre-commit): auto fixes"
  autoupdate_commit_msg: "chore(pre-commit): autoupdate hooks"

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        additional_dependencies: [ ]
        args: [ "--fix", "--exit-non-zero-on-fix" ]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        additional_dependencies: [ ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        files: ^(scripts|libs|bots)/
        additional_dependencies: [ pytest-builtin-types, types-PyYAML, types-requests, aiogram ]
        args: [ "--config-file=pyproject.toml" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
        #- id: no-commit-to-branch
        args: [ "-b", "main", "-b", "master" ]

  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest
        entry: pytest
        language: system
        pass_filenames: false
        args:
          - -q
          - --disable-warnings
          - --cov=.
          - --cov-report=term-missing
          - --cov-report=xml
          - --cov-report=html

      - id: coverage-badge-amend
        name: Amend last commit with updated badge
        language: python
        entry: python scripts/badge/badge_amend.py
        pass_filenames: false
        stages: [ post-commit ]
